schema_version: "1.0.0"
name: Red Hat ATO Pathways
metadata:
  description: Aggregates all Red Hat OpenControl content.
  maintainers:
    - Shawn Wells <shawn@redhat.com>
    - Gabe Alford <galford@redhat.com>

components:

dependencies:
  standards:
    - url: https://github.com/opencontrol/standards
      revision: master
  certifications:
    - url: https://github.com/opencontrol/certifications
      revision: master
  systems:
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: osp13
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: ocp3
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: idm
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: ansible-tower
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: rhvm
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: rhvh
      revision: opencontrol
    - url: https://github.com/ComplianceAsCode/redhat
      contextdir: coreos4
      revision: opencontrol

